# Generated by Django 3.1.5 on 2021-02-08 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=50, unique=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('date_of_expiry', models.DateField(blank=True)),
                ('stock_Available', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=50)),
                ('investigations', models.CharField(blank=True, max_length=100)),
                ('bp', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('initials', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Regim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regim', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_tabs', models.IntegerField()),
                ('pharmacy', models.BooleanField(null=True)),
                ('dose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crispy.dose')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crispy.drug')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crispy.history')),
                ('regim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crispy.regim')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historys', to='crispy.patient'),
        ),
    ]
